name: icard
description: A Didgital Business card.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts\BebasNeue-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts\SourceSansPro-Regular.ttf